services:
  # 1. DATABASE
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: galaxies_admin
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: galaxies
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U galaxies_admin -d galaxies"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. NOCODB (Database UI)
  nocodb:
    image: nocodb/nocodb:latest
    container_name: galaxies_nocodb
    restart: always
    environment:
      NC_PUBLIC_URL: "https://db.playburnrate.com"
    depends_on:
      db:
        condition: service_healthy

  # 3. GAME SERVER
  backend:
    build:
      context: .
      dockerfile: server.Dockerfile
    restart: always
    environment:
      DB_URL: "postgres://galaxies_admin:${DB_PASSWORD}@db:5432/galaxies"
      GIN_MODE: "release"
      GITHUB_KEY: ${GITHUB_KEY}
      GITHUB_SECRET: ${GITHUB_SECRET}
      DISCORD_KEY: ${DISCORD_KEY}
      DISCORD_SECRET: ${DISCORD_SECRET}
      CALLBACK_BASE_URL: "https://playburnrate.com"
    depends_on:
      db:
        condition: service_healthy

  # 4. CLIENT (Nginx)
  frontend:
    build:
      context: .
      dockerfile: client.Dockerfile
    restart: always
    depends_on:
      db:
        condition: service_healthy
      backend:
        condition: service_started
      nocodb:
        condition: service_started

  # 5. CLOUDFLARE
  tunnel:
    image: cloudflare/cloudflared:latest
    restart: always
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
